# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 388)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        Dialog.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 691, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cities = QtWidgets.QWidget()
        self.tab_cities.setObjectName("tab_cities")
        self.fr_general_cities = QtWidgets.QFrame(self.tab_cities)
        self.fr_general_cities.setGeometry(QtCore.QRect(0, 0, 681, 341))
        self.fr_general_cities.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_general_cities.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_general_cities.setObjectName("fr_general_cities")
        self.list_cities = QtWidgets.QListWidget(self.fr_general_cities)
        self.list_cities.setGeometry(QtCore.QRect(10, 40, 321, 291))
        self.list_cities.setObjectName("list_cities")
        self.lb_filtro_city = QtWidgets.QLabel(self.fr_general_cities)
        self.lb_filtro_city.setGeometry(QtCore.QRect(10, 10, 55, 16))
        self.lb_filtro_city.setObjectName("lb_filtro_city")
        self.entry_search_city = QtWidgets.QLineEdit(self.fr_general_cities)
        self.entry_search_city.setGeometry(QtCore.QRect(70, 10, 261, 22))
        self.entry_search_city.setObjectName("entry_search_city")
        self.fr_details__city = QtWidgets.QFrame(self.fr_general_cities)
        self.fr_details__city.setGeometry(QtCore.QRect(360, 10, 321, 321))
        self.fr_details__city.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_details__city.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_details__city.setObjectName("fr_details__city")
        self.lb_staticname_city = QtWidgets.QLabel(self.fr_details__city)
        self.lb_staticname_city.setGeometry(QtCore.QRect(10, 170, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.lb_staticname_city.setFont(font)
        self.lb_staticname_city.setObjectName("lb_staticname_city")
        self.lb_staticdescription_city = QtWidgets.QLabel(self.fr_details__city)
        self.lb_staticdescription_city.setGeometry(QtCore.QRect(10, 220, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.lb_staticdescription_city.setFont(font)
        self.lb_staticdescription_city.setObjectName("lb_staticdescription_city")
        self.lb_img_city = QtWidgets.QLabel(self.fr_details__city)
        self.lb_img_city.setGeometry(QtCore.QRect(10, 40, 111, 111))
        self.lb_img_city.setText("")
        self.lb_img_city.setPixmap(QtGui.QPixmap("../../../../../Pictures/reactions/bb72016e-a8f2-407a-8ee9-854823e4f28c.png"))
        self.lb_img_city.setScaledContents(True)
        self.lb_img_city.setObjectName("lb_img_city")
        self.lb_details_city = QtWidgets.QLabel(self.fr_details__city)
        self.lb_details_city.setGeometry(QtCore.QRect(10, 10, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lb_details_city.setFont(font)
        self.lb_details_city.setObjectName("lb_details_city")
        self.lb_name_city = QtWidgets.QLabel(self.fr_details__city)
        self.lb_name_city.setGeometry(QtCore.QRect(10, 190, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.lb_name_city.setFont(font)
        self.lb_name_city.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lb_name_city.setWordWrap(True)
        self.lb_name_city.setObjectName("lb_name_city")
        self.lb_description_city = QtWidgets.QLabel(self.fr_details__city)
        self.lb_description_city.setGeometry(QtCore.QRect(10, 240, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.lb_description_city.setFont(font)
        self.lb_description_city.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lb_description_city.setWordWrap(True)
        self.lb_description_city.setObjectName("lb_description_city")
        self.tabWidget.addTab(self.tab_cities, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_filtro_city.setText(_translate("Dialog", "Buscar:"))
        self.lb_staticname_city.setText(_translate("Dialog", "Nombre:"))
        self.lb_staticdescription_city.setText(_translate("Dialog", "Descripción:"))
        self.lb_details_city.setText(_translate("Dialog", "Detalles de ciudad"))
        self.lb_name_city.setText(_translate("Dialog", "TextLabel"))
        self.lb_description_city.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cities), _translate("Dialog", "Ciudades"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(w)
    w.show()
    sys.exit(app.exec_())